#!/usr/bin/env bash
set -euo pipefail

if git remote get-url github >/dev/null 2>&1; then
  git remote set-url github https://github.com/KarmaKong/khorgos.git
else
  git remote add github https://github.com/KarmaKong/khorgos.git
fi
